name: CI
on:
  push:
    branches:
      - main
    tags: '*'
  pull_request:
concurrency:
  # Skip intermediate builds: always.
  # Cancel intermediate builds: only if it is a pull request build.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}
jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }} - ${{ github.event_name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        version:
          - '1.10'
          - '1.11'
        os:
          - ubuntu-latest
        arch:
          - x64
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - uses: julia-actions/julia-downgrade-compat@v1
        if: ${{ matrix.version == '1.10' }}
      - uses: julia-actions/cache@v1
      - name: Set CAT packages to develop & resolve env
        run: |
          julia --project=test/ -e 'using Pkg;
                                    Pkg.develop(path=".");
                                    Pkg.resolve();
                                    Pkg.instantiate()'
        env:
          R_HOME: '*'
      - uses: julia-actions/julia-buildpkg@v1
      - name: Run tests
        run: |
          cd test && julia --project=. --code-coverage=user ./runtests.jl
      - uses: julia-actions/julia-processcoverage@v1
      - uses: coverallsapp/github-action@v2
        with:
          file: lcov.info
  docs:
    name: Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          miniforge-version: latest
      - uses: julia-actions/setup-julia@v1
        with:
          version: '1.10'
      - name: Set CAT packages to develop & resolve env
        run: |
          julia --project=docs/ -e 'using Pkg;
                                    Pkg.develop(path=".");
                                    Pkg.resolve();
                                    Pkg.instantiate()'
      - uses: julia-actions/julia-buildpkg@v1
        with:
          project: 'docs'
      - name: Install GitHubActions.jl in docs env
        run: |
          julia --project=docs/ -e '
            using Pkg
            Pkg.add(Pkg.PackageSpec(name="GitHubActions", version="0.1"))'
        env:
          JULIA_CONDAPKG_BACKEND: 'System'
      - name: Make docs
        run: |
          julia --project=docs/ docs/fix_r_preferences.jl &&
          USE_CAIRO_MAKIE=1 \
          JULIA_CONDAPKG_BACKEND=System \
          julia --project=docs/ -e '
            include("docs/make.jl")'
        env:
          JULIA_CONDAPKG_BACKEND: 'System'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }}
